# Generated by Django 4.1.2 on 2022-10-28 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listing_delete_auctionlistings_delete_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlistListing', to=settings.AUTH_USER_MODEL),
        ),
    ]
