# Generated by Django 4.1.2 on 2022-10-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
